#!/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby

PRFX_REPO = 'https://github.com/kylefrost/prfx'
PRFX_DIR = '/usr/local/bin'

module Tty extend self
  def blue; bold 34; end
  def white; bold 39; end
  def red; bold 31; end
  def reset; escape 0; end
  def bold n; escape "1;#{n}" end
  def underline n; escape "4;#{n}" end
  def escape n; "\033[#{n}m" if STDOUT.tty? end
end

class Array
  def shell_s
    cp = dup
    first = cp.shift
    cp.map{ |arg| arg.gsub " ", "\\ " }.unshift(first) * " "
  end
end

def warn warning
  puts "#{Tty.red}==>#{Tty.reset} #{warning.chomp}"
end

def ohai *args
    puts "#{Tty.blue}==>#{Tty.white} #{args.shell_s}#{Tty.reset}"
end

def system *args
    abort "Failed during: #{args.shell_s}" unless Kernel.system(*args)
end

def getc  # NOTE only tested on OS X
  system "/bin/stty raw -echo"
  if STDIN.respond_to?(:getbyte)
    STDIN.getbyte
  else
    STDIN.getc
  end
ensure
  system "/bin/stty -raw echo"
end

def wait_for_user
  puts
  ohai "Press RETURN to continue or any other key to abort."
  c = getc
  # we test for \r and \n because some stuff does \r instead
  abort unless c == 13 or c == 10
end

def wait_for_reinstall
  ohai "Press RETURN to reinstall or any other key to abort."
  c = getc
  # we test for \r and \n because some stuff does \r instead
  abort unless c == 13 or c == 10
end

#######################################################################
abort "Don't run this as root!" if Process.uid == 0
abort <<-EOABORT unless `groups`.split.include? "admin"
This script requires the user #{ENV['USER']} to be an Administrator. If you
still want to use this script set your user to be an Administrator in
System Preferences or `su' to a non-root user with Administrator privileges.
EOABORT

unless Dir["#{PRFX_DIR}/prfx"].empty?
  puts
  ohai "It appears prfx is already installed."
  puts
  warn "If you want to uninstall, run this command:"
  warn "sudo rm -rf #{PRFX_DIR}/prfx"
  puts
  wait_for_reinstall if STDIN.tty?
  system "sudo -v"
  ohai "Preparing the old version for update..."
  system "/usr/bin/sudo chown #{ENV['USER']}:staff /usr/local/bin/prfx"
end

if Dir["#{PRFX_DIR}/prfx"].empty?
  puts
  ohai "This script will install:"
  puts
  puts "prfx"
  puts
  wait_for_user if STDIN.tty?
  system "/usr/bin/sudo -v"
end

Dir.chdir PRFX_DIR  do
    ohai "Downloading and installing PRFX..."
    system "/usr/bin/curl -fsSL -O -s https://raw.github.com/kylefrost/prfx/master/prfx"
    ohai "Setting permissions..."
    system "/bin/chmod a+x prfx"
end
